AWSTemplateFormatVersion: 2010-09-09
Description: Automated Patch Solution Using AWS SSM
Metadata:
  License: >-
    Any code, applications, scripts, templates, proofs of concept, documentation
    and other items provided by AWS under this SOW are "AWS Content," as defined
    in the Agreement, and are provided for illustration purposes only. All such
    AWS Content is provided solely at the option of AWS, and is subject to the
    terms of the Addendum and the Agreement. Customer is solely responsible for
    using, deploying, testing, and supporting any code and applications provided
    by AWS under this SOW.
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Linux Patching Configuration
        Parameters:
          - CreateAmzLinuxBaseline
          - AmzLinuxApprovedPatchesComplianceLevel
          - AmzLinuxApprovedPatches
          - AmzLinuxRejectedPatches
          - AmzLinuxApproveAfterDays
          - AmzLinuxSchedule
          - AmzLinuxMaxConcurrency
          - AmzLinuxPatchGroup
      - Label:
          default: Windows Patching Configuration
        Parameters:
          - CreateWinBaseline
          - WinApprovedPatchesComplianceLevel
          - WinApprovedPatches
          - WinRejectedPatches
          - WinApproveAfterDays
          - WinSchedule
          - WinMaxConcurrency
          - WinPatchGroup
      - Label:
          default: Redhat Patching Configuration
        Parameters:
          - CreateRedhatBaseline
          - RedhatApprovedPatchesComplianceLevel
          - RedhatApprovedPatches
          - RedhatRejectedPatches
          - RedhatApproveAfterDays
          - RedhatSchedule
          - RedhatMaxConcurrency
          - RedhatPatchGroup
Parameters:
  AmzLinuxApprovedPatchesComplianceLevel:
    Description: >-
      The compliance level for approved patches. This means that if an approved
      patch is reported as missing, this is the severity of the compliance
      violation. Valid compliance severity levels include the following:
      CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL and UNSPECIFIED. The default
      value is
    Type: String
    AllowedValues:
      - CRITICAL
      - HIGH
      - MEDIUM
      - LOW
      - INFORMATIONAL
      - UNSPECIFIED
    Default: UNSPECIFIED
  WinApprovedPatchesComplianceLevel:
    Description: >-
      The compliance level for approved patches. This means that if an approved
      patch is reported as missing, this is the severity of the compliance
      violation. Valid compliance severity levels include the following:
      CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL and UNSPECIFIED.
    Type: String
    AllowedValues:
      - CRITICAL
      - HIGH
      - MEDIUM
      - LOW
      - INFORMATIONAL
      - UNSPECIFIED
    Default: UNSPECIFIED
  RedhatApprovedPatchesComplianceLevel:
    Description: >-
      The compliance level for approved patches. This means that if an approved
      patch is reported as missing, this is the severity of the compliance
      violation. Valid compliance severity levels include the following:
      CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL and UNSPECIFIED.
    Type: String
    AllowedValues:
      - CRITICAL
      - HIGH
      - MEDIUM
      - LOW
      - INFORMATIONAL
      - UNSPECIFIED
    Default: UNSPECIFIED
  CreateAmzLinuxBaseline:
    Description: Create patch baseline for Amazon Linux
    Type: String
    AllowedValues:
      - 'True'
      - 'False'
    Default: 'True'
  CreateWinBaseline:
    Description: Create patch baseline for Microsoft Windows Servers
    Type: String
    AllowedValues:
      - 'True'
      - 'False'
    Default: 'True'
  CreateRedhatBaseline:
    Description: Create patch baseline for Redhat Enterprise
    Type: String
    AllowedValues:
      - 'True'
      - 'False'
    Default: 'True'
  AmzLinuxApproveAfterDays:
    Description: >-
      The number of days after the release date of each patch that matches the
      rule to mark the patch as approved in the patch baseline.
    Type: Number
    Default: 10
  WinApproveAfterDays:
    Description: >-
      The number of days after the release date of each patch that matches the
      rule to mark the patch as approved in the patch baseline.
    Type: Number
    Default: 10
  RedhatApproveAfterDays:
    Description: >-
      The number of days after the release date of each patch that matches the
      rule to mark the patch as approved in the patch baseline.
    Type: Number
    Default: 10
  AmzLinuxApprovedPatches:
    Description: >-
      (Optional) A list of explicitly approved patches for the baseline (i.e.
      AmazonLinux2017.09,AmazonLinux2017.03...)
    Type: String
  AmzLinuxRejectedPatches:
    Description: >-
      (Optional) A list of explicitly rejected patches for the baseline (i.e.
      AmazonLinux2017.09,AmazonLinux2017.03...)
    Type: String
  RedhatApprovedPatches:
    Description: >-
      (Optional) A list of explicitly approved patches for the baseline (i.e.
      CVE-2018-0700,CVE-2018-0710...)
    Type: String
  RedhatRejectedPatches:
    Description: >-
      (Optional) A list of explicitly rejected patches for the baseline (i.e.
      CVE-2018-0700,CVE-2018-0710...)
    Type: String
  WinApprovedPatches:
    Description: >-
      (Optional) A list of explicitly approved patches for the baseline (i.e.
      KB1,KB2...)
    Type: String
  WinRejectedPatches:
    Description: >-
      (Optional) A list of explicitly rejected patches for the baseline (i.e.
      KB1,KB2...)
    Type: String
  AmzLinuxSchedule:
    Description: >-
      The schedule of the Maintenance Window in the form of a cron or rate
      expression, see Cron and Rate Expressions for Systems Manager:
      https://docs.aws.amazon.com/systems-manager/latest/userguide/reference-cron-and-rate-expressions.html
    Type: String
    Default: cron(0 */5 * * * ? *)
  WinSchedule:
    Description: >-
      The schedule of the Maintenance Window in the form of a cron or rate
      expression, see Cron and Rate Expressions for Systems Manager:
      https://docs.aws.amazon.com/systems-manager/latest/userguide/reference-cron-and-rate-expressions.html
    Type: String
    Default: cron(0 */5 * * * ? *)
  RedhatSchedule:
    Description: >-
      The schedule of the Maintenance Window in the form of a cron or rate
      expression, see Cron and Rate Expressions for Systems Manager:
      https://docs.aws.amazon.com/systems-manager/latest/userguide/reference-cron-and-rate-expressions.html
    Type: String
    Default: cron(0 */5 * * * ? *)
  AmzLinuxMaxConcurrency:
    Description: >-
      Specify either a number or a percentage of instances on which to run the
      command at the same time. Note: If you selected targets by choosing Amazon
      EC2 tags, and you are not certain how many instances use the selected
      tags, then limit the number of instances that can run the document at the
      same time by specifying a percentage.
    Type: String
    MinLength: '1'
    Default: '1'
  WinMaxConcurrency:
    Description: >-
      Specify either a number or a percentage of instances on which to run the
      command at the same time. Note: If you selected targets by choosing Amazon
      EC2 tags, and you are not certain how many instances use the selected
      tags, then limit the number of instances that can run the document at the
      same time by specifying a percentage.
    Type: String
    MinLength: '1'
    Default: '1'
  RedhatMaxConcurrency:
    Description: >-
      Specify either a number or a percentage of instances on which to run the
      command at the same time. Note: If you selected targets by choosing Amazon
      EC2 tags, and you are not certain how many instances use the selected
      tags, then limit the number of instances that can run the document at the
      same time by specifying a percentage.
    Type: String
    MinLength: '1'
    Default: '1'
  AmzLinuxPatchGroup:
    Description: >-
      The name of the patch group (EC2 Tag) to be registered with the patch
      baseline. (i.e. Amz_Linux_Patch_Group)
    Type: String
    MinLength: '1'
    Default: Amz_Linux_Patch_Group
  WinPatchGroup:
    Description: >-
      The name of the patch group (EC2 Tag) to be registered with the patch
      baseline. (i.e. Win_Patch_Group)
    Type: String
    MinLength: '1'
    Default: Win_Patch_Group
  RedhatPatchGroup:
    Description: >-
      The name of the patch group (EC2 Tag) to be registered with the patch
      baseline. (i.e. Redhat_Patch_Group)
    Type: String
    MinLength: '1'
    Default: Redhat_Patch_Group
Conditions:
  HasAmzLinuxApprovedPatches: !Not
    - !Equals
      - ''
      - !Ref AmzLinuxApprovedPatches
  HasRedhatApprovedPatches: !Not
    - !Equals
      - ''
      - !Ref RedhatApprovedPatches
  HasWinApprovedPatches: !Not
    - !Equals
      - ''
      - !Ref WinApprovedPatches
  HasAmzLinuxRejectedPatches: !Not
    - !Equals
      - ''
      - !Ref AmzLinuxRejectedPatches
  HasRedhatRejectedPatches: !Not
    - !Equals
      - ''
      - !Ref RedhatRejectedPatches
  HasWinRejectedPatches: !Not
    - !Equals
      - ''
      - !Ref WinRejectedPatches
  AmzLinxBaseline: !Equals
    - !Ref CreateAmzLinuxBaseline
    - 'True'
  WinBaseline: !Equals
    - !Ref CreateWinBaseline
    - 'True'
  RedhatBaseline: !Equals
    - !Ref CreateRedhatBaseline
    - 'True'
Resources:
  AutomationServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole'
      Path: /
      RoleName: AutomationServiceRole
      Policies:
        - PolicyName: passrole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource:
                  - !GetAtt
                    - ManagedInstanceRole
                    - Arn
  ManagedInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ManagedInstanceRole
      InstanceProfileName: ManagedInstanceProfile
  ManagedInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM'
      Path: /
  AmzLinuxPatchBaseline:
    Type: 'AWS::SSM::PatchBaseline'
    Condition: AmzLinxBaseline
    Properties:
      OperatingSystem: AMAZON_LINUX_2
      ApprovedPatches: !If
        - HasAmzLinuxApprovedPatches
        - !Ref AmzLinuxApprovedPatches
        - !Ref 'AWS::NoValue'
      Description: Amazon Linux 2 baseline with all latest updates
      ApprovedPatchesComplianceLevel: !Ref AmzLinuxApprovedPatchesComplianceLevel
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Key: SEVERITY
                  Values:
                    - Critical
            ComplianceLevel: CRITICAL
            ApproveAfterDays: !Ref AmzLinuxApproveAfterDays
      #GlobalFilters:
      #  PatchFilters:
      #    - Key: PRODUCT
      #      Values:
      #        - AmazonLinux2017.09
      Name: AmzLinuxPatchBaseline
      RejectedPatches: !If
        - HasAmzLinuxRejectedPatches
        - !Ref AmzLinuxRejectedPatches
        - !Ref 'AWS::NoValue'
  WindowsPatchBaseline:
    Type: 'AWS::SSM::PatchBaseline'
    Condition: WinBaseline
    Properties:
      OperatingSystem: WINDOWS
      Description: Windows baseline with all latest updates
      ApprovedPatches: !If
        - HasWinApprovedPatches
        - !Ref WinApprovedPatches
        - !Ref 'AWS::NoValue'
      ApprovedPatchesComplianceLevel: !Ref WinApprovedPatchesComplianceLevel
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Key: MSRC_SEVERITY
                  Values:
                    - Critical
                    - Important
                - Key: CLASSIFICATION
                  Values:
                    - CriticalUpdates
                    - SecurityUpdates
            ApproveAfterDays: !Ref WinApproveAfterDays
      Name: WinPatchBaseline
      RejectedPatches: !If
        - HasWinRejectedPatches
        - !Ref WinRejectedPatches
        - !Ref 'AWS::NoValue'
  RedhatPatchBaseline:
    Type: 'AWS::SSM::PatchBaseline'
    Condition: RedhatBaseline
    Properties:
      OperatingSystem: REDHAT_ENTERPRISE_LINUX
      Description: Baseline with all latest updates
      ApprovedPatches: !If
        - HasRedhatApprovedPatches
        - !Ref RedhatApprovedPatches
        - !Ref 'AWS::NoValue'
      ApprovedPatchesComplianceLevel: !Ref RedhatApprovedPatchesComplianceLevel
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Key: SEVERITY
                  Values:
                    - Critical
            ComplianceLevel: CRITICAL
            ApproveAfterDays: !Ref RedhatApproveAfterDays
      Name: RedhatPatchBaseline
      RejectedPatches: !If
        - HasRedhatRejectedPatches
        - !Ref RedhatRejectedPatches
        - !Ref 'AWS::NoValue'
  AmzLinuxMaintanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Condition: AmzLinxBaseline
    Properties:
      AllowUnassociatedTargets: 'False'
      Cutoff: '1'
      Schedule: !Ref AmzLinuxSchedule
      Duration: '4'
      Name: AmzLinuxMaintenanceWindow
  WinMaintanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Condition: WinBaseline
    Properties:
      AllowUnassociatedTargets: 'False'
      Cutoff: '1'
      Schedule: !Ref WinSchedule
      Duration: '4'
      Name: WinPatchMaintenanceWindow
  RedhatMaintanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Condition: RedhatBaseline
    Properties:
      AllowUnassociatedTargets: 'False'
      Cutoff: '1'
      Schedule: !Ref RedhatSchedule
      Duration: '4'
      Name: RedhatPatchMaintenanceWindow
  AmzLinuxMaintanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Condition: AmzLinxBaseline
    Properties:
      Description: Amz_Linux_Maintenance_Window_Target
      WindowId: !Ref AmzLinuxMaintanceWindow
      ResourceType: INSTANCE
      Targets:
        - Key: 'tag:Patch Group'
          Values:
            - !Ref AmzLinuxPatchGroup
  WinMaintanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Condition: WinBaseline
    Properties:
      Description: Win_Maintenance_Window_Target
      WindowId: !Ref WinMaintanceWindow
      ResourceType: INSTANCE
      Targets:
        - Key: 'tag:Patch Group'
          Values:
            - !Ref WinPatchGroup
  RedhatMaintanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Condition: RedhatBaseline
    Properties:
      Description: Amz_Linux_Maintenance_Window_Target
      WindowId: !Ref RedhatMaintanceWindow
      ResourceType: INSTANCE
      Targets:
        - Key: 'tag:Patch Group'
          Values:
            - !Ref RedhatPatchGroup
  AmzLinuxMaintanceWindowTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Condition: AmzLinxBaseline
    Properties:
      MaxErrors: '1'
      Description: Amz_Linux_Maintenance_Window_Task
      ServiceRoleArn: !GetAtt
        - AutomationServiceRole
        - Arn
      Priority: '1'
      MaxConcurrency: !Ref AmzLinuxMaxConcurrency
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref AmzLinuxMaintanceWindowTarget
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref AmzLinuxMaintanceWindow
      TaskParameters:
        Operation:
          Values:
            - Install
      TaskType: RUN_COMMAND
  WinMaintanceWindowTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      MaxErrors: '1'
      Description: Win_Maintenance_Window_Task
      ServiceRoleArn: !GetAtt
        - AutomationServiceRole
        - Arn
      Priority: '1'
      MaxConcurrency: !Ref WinMaxConcurrency
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref WinMaintanceWindowTarget
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref WinMaintanceWindow
      TaskParameters:
        Operation:
          Values:
            - Install
      TaskType: RUN_COMMAND
  RedhatMaintanceWindowTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Condition: RedhatBaseline
    Properties:
      MaxErrors: '1'
      Description: Redhat_Maintenance_Window_Task
      ServiceRoleArn: !GetAtt
        - AutomationServiceRole
        - Arn
      Priority: '1'
      MaxConcurrency: !Ref RedhatMaxConcurrency
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref RedhatMaintanceWindowTarget
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref RedhatMaintanceWindow
      TaskParameters:
        Operation:
          Values:
            - Install
      TaskType: RUN_COMMAND
